book: 
  chapters:
    - index.qmd
    - part: "Examples"
      chapters: 
        - chapters/01-data-and-models.qmd
        - chapters/02-black-box-classification.qmd
        - chapters/20-introduction-prediction.qmd
        - chapters/21-feature-engineering-and-overfitting.qmd
    